### ISSUE TITLE
test_svm_backward.py always chooses trivial features [0,1,...,1022,1023]

### ISSUE THREAD

**Issue by hkayabilisim** [jundongl/scikit-feature#11]
Hi,

In the test_svm_backward.py test file, the features chosen with the svm_backward selection method is always the same ([0,1,...,1023]).

**Comment by vivian1993** [comment]
Hi,
Since in the test_svm_backward.py test file, we set input "n_selected_features" of the function svm_backward(X, y, n_selected_features) as the whole features. Of course, the return result would be the whole feature. For example, if you set set input "n_selected_features" of the function svm_backward(X, y, n_selected_features) as (the whole features-1), you will get want you want. 
Tips: svm_backward selection method will be efficient when you want to select a lot of features. If you only want to select small set of features, I recommend you to use svm_forward selection method.

**Comment by hkayabilisim** [comment]
Thank you for your answer.
